# Generated by Django 6.0.2 on 2026-02-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('program', models.CharField(max_length=120)),
                ('graduation_year', models.PositiveIntegerField()),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self-employed'), ('STUDENT', 'Further Studies'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('is_job_related', models.BooleanField(default=False)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='account.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='FurtherStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_studies', to='account.alumni')),
            ],
        ),
    ]
