# Generated by Django 6.0.3 on 2026-03-18 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alumni_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PROFILE_UPDATE', 'Profile Updated'), ('EMPLOYMENT_ADD', 'Employment Added'), ('EMPLOYMENT_UPDATE', 'Employment Updated'), ('STUDY_ADD', 'Study Added'), ('LOGIN', 'Login'), ('PROFILE_PHOTO_UPDATE', 'Profile Photo Updated')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year', 'last_name', 'first_name'], 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='furtherstudy',
            options={'ordering': ['-start_year'], 'verbose_name_plural': 'Further Studies'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_photos/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='seniority_level',
            field=models.CharField(choices=[('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead/Manager'), ('DIRECTOR', 'Director/Executive'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='employment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='e.g., Computer Science, Business Administration', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='school_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ONGOING', max_length=20),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['student_id'], name='account_alu_student_5ca378_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['graduation_year'], name='account_alu_graduat_b8123a_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['employment_status'], name='account_alu_employm_aff707_idx'),
        ),
        migrations.AddIndex(
            model_name='furtherstudy',
            index=models.Index(fields=['alumni', 'status'], name='account_fur_alumni__0694c9_idx'),
        ),
        migrations.AddField(
            model_name='activity',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='account.alumni'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['alumni', 'created_at'], name='account_act_alumni__43df13_idx'),
        ),
    ]
