# Generated by Django 6.0.3 on 2026-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_activity_alter_alumni_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PROFILE_UPDATE', 'Profile Updated'), ('EMPLOYMENT_ADD', 'Employment Added'), ('EMPLOYMENT_UPDATE', 'Employment Updated'), ('STUDY_ADD', 'Study Added'), ('LOGIN', 'Login'), ('NETWORK_CONNECT', 'Network Connected'), ('PROFILE_PHOTO_UPDATE', 'Profile Photo Updated')], max_length=30),
        ),
    ]
