# Generated by Django 6.0.3 on 2026-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main text (e.g., 'Connect With Your')", max_length=100)),
                ('subtitle', models.CharField(help_text="Golden highlighted text (e.g., 'Alumni Community')", max_length=100)),
                ('description', models.TextField(help_text='Slide description paragraph')),
                ('background_image', models.ImageField(help_text='Background image for the slide', upload_to='carousel/')),
                ('primary_button_text', models.CharField(help_text="Primary button label (e.g., 'Learn More')", max_length=100)),
                ('primary_button_url', models.CharField(help_text='Where primary button links to', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, help_text='Secondary button label (optional)', max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, help_text='Where secondary button links to (optional)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slide position (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active slides appear on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Value name (e.g., 'Community')", max_length=50)),
                ('icon_class', models.CharField(choices=[('fas fa-handshake', 'Handshake (Community)'), ('fas fa-lightbulb', 'Lightbulb (Innovation)'), ('fas fa-chart-line', 'Chart Line (Excellence)'), ('fas fa-users', 'Users (Integrity)'), ('fas fa-globe', 'Globe (Inclusivity)'), ('fas fa-rocket', 'Rocket (Growth)'), ('fas fa-heart', 'Heart'), ('fas fa-star', 'Star'), ('fas fa-brain', 'Brain'), ('fas fa-shield-alt', 'Shield'), ('fas fa-target', 'Target'), ('fas fa-crown', 'Crown')], help_text='Choose an icon for this value', max_length=50)),
                ('description', models.TextField(help_text='Description of this core value')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the values grid')),
                ('is_active', models.BooleanField(default=True, help_text='Only active values appear on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about_hero', 'About Section - Hero Title'), ('about_description', 'About Section - Description'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement')], help_text='Which section this content belongs to', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Section title (if applicable)', max_length=300)),
                ('content', models.TextField(help_text='Main content text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Technological Institute of the Philippines - Manila', max_length=200)),
                ('tagline', models.CharField(default='T.I.P.ians Connect: Alumni Tracer System for IT Graduates', max_length=255)),
                ('primary_color', models.CharField(default='#FFD700', help_text='Primary brand color (gold) - use hex format #RRGGBB', max_length=7)),
                ('secondary_color', models.CharField(default='#28282B', help_text='Secondary brand color (dark) - use hex format', max_length=7)),
                ('copyright_year', models.IntegerField(default=2024, help_text='Year for copyright notice')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
