# Generated by Django 6.0.2 on 2026-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_employmentstatus_feature_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='date_left',
            field=models.DateField(blank=True, null=True, verbose_name='Date Left'),
        ),
    ]
