# Generated by Django 6.0.2 on 2026-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_employmentstatus_feature_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
