# Generated by Django 6.0.2 on 2026-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_employment_date_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='created_via_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employment',
            name='voice_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='voice_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='created_via_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='voice_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furtherstudy',
            name='voice_updated',
            field=models.BooleanField(default=False),
        ),
    ]
