# Generated by Django 6.0.2 on 2026-03-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_announcement'),
        ('account', '0009_alumni_is_verified'),
    ]

    operations = [
    ]
