# Generated by Django 6.0.2 on 2026-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_0008_announcement_0009_alumni_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='created_via_voice',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='voice_transcript',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='voice_updated',
        ),
        migrations.RemoveField(
            model_name='furtherstudy',
            name='created_via_voice',
        ),
        migrations.RemoveField(
            model_name='furtherstudy',
            name='voice_transcript',
        ),
        migrations.RemoveField(
            model_name='furtherstudy',
            name='voice_updated',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PROFILE_UPDATE', 'Profile Updated'), ('EMPLOYMENT_ADD', 'Employment Added'), ('EMPLOYMENT_UPDATE', 'Employment Updated'), ('EMPLOYMENT_DELETE', 'Employment Deleted'), ('STUDY_ADD', 'Study Added'), ('STUDY_UPDATE', 'Study Updated'), ('STUDY_DELETE', 'Study Deleted'), ('LOGIN', 'Login'), ('NETWORK_CONNECT', 'Network Connected'), ('PROFILE_PHOTO_UPDATE', 'Profile Photo Updated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set True when alumni information is verified (e.g. by admin).'),
        ),
    ]
