# Generated by Django 6.0.2 on 2026-04-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_employment_created_via_voice_and_more'),
        ('account', '0011_remove_employment_date_left_and_more'),
    ]

    operations = [
    ]
