# Generated by Django 6.0.2 on 2026-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_employment_created_via_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='admin_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
