# Generated by Django 6.0.2 on 2026-04-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_siteconfig_admin_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptor', models.TextField()),
            ],
        ),
    ]
