# Generated by Django 5.2.3 on 2026-04-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_siteconfig_admin_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
