# Generated by Django 5.2.3 on 2026-04-06 05:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alumni_bio_alumni_facebook_url_alumni_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Square image, at least 200x200px (JPG, PNG). Max 5MB', null=True, upload_to='alumni_photos/', validators=[account.models.validate_image_file]),
        ),
    ]
