# Generated by Django 5.2.12 on 2026-04-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_adminface'),
        ('account', '0017_re_add_employment_date_left'),
    ]

    operations = [
    ]
