# Generated by Django 5.2.3 on 2026-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_merge_0015_adminface_0017_re_add_employment_date_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='admin_face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
