# Generated by Django 5.2.3 on 2026-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_siteconfig_admin_face_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PROFILE_UPDATE', 'Profile Updated'), ('EMPLOYMENT_CREATE', 'Employment Added'), ('EMPLOYMENT_UPDATE', 'Employment Updated'), ('EMPLOYMENT_DELETE', 'Employment Deleted'), ('STUDY_CREATE', 'Study Added'), ('STUDY_UPDATE', 'Study Updated'), ('STUDY_DELETE', 'Study Deleted'), ('LOGIN', 'Login'), ('NETWORK_CONNECT', 'Network Connected'), ('PROFILE_PHOTO_UPDATE', 'Profile Photo Updated')], max_length=30),
        ),
    ]
