# Generated by Django 5.2.3 on 2026-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='furtherstudy',
            name='created_via_voice',
            field=models.BooleanField(default=False),
        ),
    ]