# Generated by Django 5.2.3 on 2026-04-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_add_created_via_voice_to_furtherstudy'),
    ]

    operations = [
    ]
